version: '3.8'
services:
  postgres-dev:
    image: 'postgres:13'
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - database-network
  next-dev:
    build: ./
    restart: unless-stopped
    depends_on:
      - postgres-dev
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - next-modules:/usr/src/app/node_modules
      - next-build:/usr/src/app/.next
    ports:
      - 3000:3000
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
volumes:
  next-modules:
  next-build:
  database-data:
