version: '3.8'
services:
  postgres:
    container_name: postgres-test
    image: 'postgres:13'
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - database-network
  next:
    container_name: next-test
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - postgres
    env_file:
      - .env
    expose:
      - '3000'
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
