version: '3.8'
services:
  postgres-export:
    image: 'postgres:13'
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - database-network
  next-export:
    build:
      context: ./
      dockerfile: Dockerfile.export
    depends_on:
      - postgres-export
    env_file:
      - .env
    environment:
      - NEXT_EXPORT_MODE=1
      - NEXT_PUBLIC_BASE_PATH
    volumes:
      - ./out:/usr/src/app/out
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
