FROM node:14-alpine

RUN apk add --no-cache libc6-compat

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

COPY ./ ./

CMD npx wait-on tcp:postgres:5432 && npm run migrate && npm run export