version: '3.8'
services:
  postgres-test:
    image: 'postgres:13'
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - database-network
  next-test:
    build:
      context: ./
      dockerfile: Dockerfile.test
    depends_on:
      - postgres-test
    env_file:
      - .env
    expose:
      - '3000'
    networks:
      - database-network
networks:
  database-network:
    driver: bridge
