name: Test and Export Next then Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: docker-compose -f "docker-compose.test.yml" up --build --exit-code-from next-test

  export_deploy:
    needs: test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_BASE_PATH: /solita-assignment

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Export Next
        run: docker-compose -f "docker-compose.export.yml" up --build --exit-code-from next-export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          force_orphan: true
